name: build
on: push

jobs:
  build:
    strategy:
      matrix:
        java: [ 17-jdk ]
    runs-on: ubuntu-20.04
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # Build

      - name: Build Fabric
        run: ./gradlew :fabric:build

      - name: Build Forge
        run: ./gradlew :forge:build

      # Upload

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./*/build/libs/

      - name: Upload artifacts (Fabric)
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts (Fabric)
          path: ./fabric/build/libs/

      - name: Upload artifacts (Forge)
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts (Forge)
          path: ./forge/build/libs/
